name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Build
      run: |
        npm run build
        # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        touch docs/.vuepress/dist/.nojekyll
        # https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site
        echo towardsliberty.com > docs/.vuepress/dist/CNAME
      env:
        CI: true
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: docs/.vuepress/dist/
        GH_PAT: ${{ secrets.GH_PAT }}
